import '@/src/@shared/style/globals.css';

import type { Metadata } from 'next';
import { QueryProvider } from '@/src/@infrastructure/store/server/query-provider';
import { ErrorBoundary } from '@suspensive/react';
import React from 'react';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary fallback={<div>hi</div>}>
          <React.Suspense fallback={<div>loading</div>}>
            <QueryProvider>{children}</QueryProvider>
          </React.Suspense>
        </ErrorBoundary>
      </body>
    </html>
  );
}
