import '@/src/@shared/style/globals.css';

import type { Metadata } from 'next';
import { QueryProvider } from '@/src/@infrastructure/store/server/query-provider';
import React from 'react';
import { PubSubProvider } from '@/event/event-comp';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PubSubProvider
          handler={{
            USER_CREATED: [
              (event) => {
                console.log('created event', event);
              },
            ],
            USER_DELETED: [
              (event) => {
                console.log('deleted', event);
              },
            ],
          }}
        >
          <QueryProvider>{children}</QueryProvider>
        </PubSubProvider>
      </body>
    </html>
  );
}
