import '@/src/@shared/style/globals.css';

import type { Metadata } from 'next';
import { QueryProvider } from '@/src/@infrastructure/store/server/query-provider';
import React from 'react';
import { PubSubProvider } from '@/src/@infrastructure/pub-sub-example/provider';
import { LogProvider } from './_component/log-provider';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PubSubProvider>
          <LogProvider>
            <QueryProvider>{children}</QueryProvider>
          </LogProvider>
        </PubSubProvider>
      </body>
    </html>
  );
}
