import type { Metadata } from 'next';
import { XION_NEXT_FONT } from '@/style/font/font';
import './globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={XION_NEXT_FONT.className}>{children}</body>
    </html>
  );
}
